### ISSUE TITLE
Another color for `julia>` in help

### ISSUE THREAD

**Issue by innerlee** [KristofferC/OhMyREPL.jl#100]
![image](https://user-images.githubusercontent.com/9464825/30511049-82635d58-9b03-11e7-97d4-724963d7ebf0.png)

The first two `julia>` is from the help text. 
And it is easily confuse people. 
```text
Wait, did I just typed "@inferred max(1,2)"?
...
```
:confused: 
```text
...
Ahh relax, just a help text.
```
:smiley:

**Comment by KristofferC** [comment]
https://github.com/KristofferC/OhMyREPL.jl/pull/101
