### ISSUE TITLE
Bracket completion of } for Reduce.jl compatibility

### ISSUE THREAD

**Issue by chakravala** [KristofferC/OhMyREPL.jl#102]
One issue with OhMyREPL that has always been bugging me is the bracket comletion for `{`.

When I type a normal bracket like `(`, then the prompt will correctly fill in the other half `)`. No problem there.

However, when I type `{` key, fill in some stuff, and then press the `}` key to close it off; then an extra `}` is insterted. So what I end up with is
```Julia
julia> {some text}}
```
This only happens with the `{` bracket and it happens every time.

**Comment by KristofferC** [comment]
Interesting. That does not happen for me, see e.g. https://asciinema.org/a/cY1Xu0xj8xlTFZgyHY0v9shYS. Also, the code that does this does not do anything different with `{` compared to `(`. Anything that is "special" with your setup that could cause this?

**Comment by chakravala** [comment]
Now that I think of it, yes there is something special about my setup.

In my `.juliarc.jl` I also have
```Julia
using Reduce
using OhMyREPL
```
I am the creator of the [Reduce.jl](https://github.com/chakravala/Reduce.jl) package. My package also provides a REPL feature which appears when the `}` button is pressed. It is a `reduce>` terminal for interacting with the REDUCE computer algebra system. In order to make the package work nicely on julia startup I had to add a line of code that checks if `OhMyREPL` is loaded:
```Julia
function Load()
    ## some stuff to do on load time
    if isdefined(Base,:active_repl) && isinteractive()
        eval(s)
        repl_init(Base.active_repl)
    else
        atreplinit() do repl
            eval(s)
            !isdefined(Main,:OhMyREPL) && (repl.interface = Base.REPL.setup_interface(repl))
            repl_init(Base.active_repl); print('\n')
end; end; end
```
That part works fine. But now I realize that this issue I am having with the Bracket matching in OhMyREPL must somehow be caused by the `}` key that activates the `reduce>` REPL.

This REPL is defined in [repl.jl](https://github.com/chakravala/Reduce.jl/blob/master/src/repl.jl), which is based on the Maxima.jl package's REPL.

Not sure how to work around this issue though, to make both packages fully compatible.

**Comment by chakravala** [comment]
The reason I picked `}` as the key to activate the `reduce>` REPL is because I thought it would be one of the least likely keys to have a conflict with anything else hahaha

**Comment by KristofferC** [comment]
If you add a print statement to your `}` keybinding in your `repl.jl`, does it fire when you write the terminating `}`. In that case, my bracket-completion and the line here: https://github.com/chakravala/Reduce.jl/blob/master/src/repl.jl#L92 both insert `}`.

**Comment by chakravala** [comment]
Yes, so one package needs to add some code that checks whether it is appropriate to insert or not. If I add it to repl.jl on that line, it needs to check whether any opening brackets are already inserted, otherwise your package could leave out the insertion if it detects the Reduce module

**Comment by chakravala** [comment]
Fixed with: https://github.com/chakravala/Reduce.jl/blob/master/src/repl.jl#L114-L122

**Comment by KristofferC** [comment]
Great :)
