### ISSUE TITLE
can't paste multi-line code

### ISSUE THREAD

**Issue by Ken-B** [KristofferC/OhMyREPL.jl#113]
First of all, thank you for this great package! 

This is just a minor issue, but I thought to ask anyway, as I run into this regularly lately.

Is there a way to copy past multi-line code without auto-closing the brackets?

E.g. 
```
x = 2 * (3 
    +5)
```
will copy past into 
```
julia> x = 2 * (3 )
6

julia>     +5)
```
Best regards,
Ken

**Comment by KristofferC** [comment]
This is windows I take it? The problem with copy-pasting on Windows is that it is literally like manually writing the keys really quickly. And when the `(` is pressed, the auto bracket matcher happily inserts a `)` for you. The only way to solve this on Windows is to disable the bracket matcher with `enable_autocomplete_brackets(false)`.

**Comment by Ken-B** [comment]
Indeed, it's on windows (PuTTY). Just checked and on mac I don't get this behaviour. 
Thanks for the explanation and workaround!
Feel free to close if you don't think it's feasible or worthwhile to fix.

**Comment by KristofferC** [comment]
This is now disabled by default on windows.
