### ISSUE TITLE
OhMyREPL in Vim?

### ISSUE THREAD

**Issue by KadeG** [KristofferC/OhMyREPL.jl#117]
Is it possible to use OhMyREPL in Vim? [Julia-vim](https://github.com/JuliaEditorSupport/julia-vim) is missing lots of nice things which OhMyREPL has (highlighting for user-defined functions, rainbow brackets, etc).

**Comment by KristofferC** [comment]
When you mean "use in Vim" do you mean to use it in the text editor itself? In that case, the answer is no, OhMyREPL only works inside the Julia REPL. However, Vim has a large number of plugins so stuff like rainbow-brackets might be available, perhaps https://github.com/luochen1990/rainbow.

**Comment by KadeG** [comment]
Yes, I meant using it as the syntax highlighting schema in Vim. Thanks for the quick response!

**Comment by nabeel-hasan** [comment]
I really wish if ohmyrelp worked in the vim editor
