### ISSUE TITLE
Would OhMyREPL like an enhanced Console Logger?

### ISSUE THREAD

**Issue by oxinabox** [KristofferC/OhMyREPL.jl#121]
I have created a (slightly) enhanced ConsoleLogger,
currently at 
https://github.com/oxinabox/OhMyLog.jl
(it is basically forked from stdlib/Logger.jl)

I feel like it might be a good fit for OhMyREPL. (Though feel free to say no.)
Like OhMyREPL it is a package designed to be loaded at start-up, to enhance the REPL experience.

See 
[![demo](https://asciinema.org/a/Cl5lps1KrhprTIvhipTPZfWNC.png)](https://asciinema.org/a/Cl5lps1KrhprTIvhipTPZfWNC?t=42)

**Comment by oxinabox** [comment]
Have you had time to give this a think?

It now does progress bars.
Which is real nice.

**Comment by KristofferC** [comment]
Sorry for late reply. Sure, seems like a good thing in this package :)

**Comment by oxinabox** [comment]
Alright,
I'll make a PR
