### ISSUE TITLE
stuff after # in branches highlighted as comments

### ISSUE THREAD

**Issue by mkborregaard** [KristofferC/OhMyREPL.jl#125]
I guess it's really a Tokenize.jl thing.

<img width="610" alt="skaermbillede 2018-08-30 kl 21 45 51" src="https://user-images.githubusercontent.com/8429802/44875410-612dc580-ac9e-11e8-80e4-4d3c4ed2d18d.png">

**Comment by mkborregaard** [comment]
Because it's too difficult to do right? (yes it's really nice for `help`)

**Comment by KristofferC** [comment]
Maybe not too difficult. Just need to be selective where we update the keybindings.
