### ISSUE TITLE
Completion for square brackets does not advance cursor when closing bracket is typed

### ISSUE THREAD

**Issue by ikselven** [KristofferC/OhMyREPL.jl#128]
If there's already a `]` on the REPL as a consequence of having typed `[` earlier, typing `]` inserts another closing bracket instead of moving the cursor beyond the existing one, like it is done with `)` or `}` or `"`. This is especially annoying when working with Dicts, Arrays and Array-like structures.

Steps:
1. start a Julia REPL with OhMyREPL active
2. type in `foo = [1, 2`
3. type `]`

Expected Result:
the line buffer contains `foo = [1, 2]` and cursor is right of `]`

Actual Result:
the line buffer contains `foo = [1, 2]]` and cursor is between the `]`

Is it a bug or a limitation because of `]` being used to enter `pkg`-mode?

**Comment by KristofferC** [comment]
Probably a bug that got introduced when I tried to fix entering Pkg REPL mode to work.

**Comment by iamed2** [comment]
I keep running into this.

**Comment by ssfrr** [comment]
Are this and #166 duplicates?

**Comment by iamed2** [comment]
Yep

**Comment by KristofferC** [comment]
Duop of #166
