### ISSUE TITLE
Remove Hack in log message id

### ISSUE THREAD

**Issue by oxinabox** [KristofferC/OhMyREPL.jl#135]
There is currently a hack in the log message id 

https://github.com/KristofferC/OhMyREPL.jl/blob/067912457f0159808204a57ed2318814b4148ecc/src/logger_core.jl#L149

It is a workaround of a bug in julia 1.0.0 and 1.0.1  (https://github.com/JuliaLang/julia/issues/28786).
It doesn't work ideally, since it just throws away the original id, and makes up its own (which removes peoples ability to set the message id.)

Now that that bug is fixed in julia master (and so will be fixed in 1.0.2),
as of https://github.com/JuliaLang/julia/pull/29878

that can be removed.

I guess it should be removed with a version guard.

**Comment by KristofferC** [comment]
Logger is removed for now
