### ISSUE TITLE
Confirm on exit

### ISSUE THREAD

**Issue by dalum** [KristofferC/OhMyREPL.jl#137]
Currently, putting:
```julia
atreplinit() do repl
    repl.options.confirm_exit = true
end
```
in my `startup.jl` file doesn't have the desired effect (it doesn't prompt when trying to exit).

**Comment by KristofferC** [comment]
And this only happens when OhMyREPL.jl is loaded?

**Comment by dalum** [comment]
Yep, sorry.  I tried putting `@eval using OhMyREPL` before/after/inside the `atreplinit()` hook, but in all cases it doesn't seem to work.

**Comment by KristofferC** [comment]
https://github.com/KristofferC/OhMyREPL.jl/blob/067912457f0159808204a57ed2318814b4148ecc/src/repl.jl#L107-L114

probably need to be fixed.
