### ISSUE TITLE
Segmentation fault when Reduce CAS loaded with OhMyREPL enabled

### ISSUE THREAD

**Issue by AtheistApe** [KristofferC/OhMyREPL.jl#138]

**Comment by AtheistApe** [comment]
After loading OhMyREPL when I try loading the[ Reduce CAS](https://github.com/chakravala/Reduce.jl) I get:

signal (11): Segmentation fault
in expression starting at no file:0
jl_compile_linfo at /buildworker/worker/package_linux64/build/src/codegen.cpp:1192
emit_invoke at /buildworker/worker/package_linux64/build/src/codegen.cpp:3095
emit_expr at /buildworker/worker/package_linux64/build/src/codegen.cpp:3894
emit_ssaval_assign at /buildworker/worker/package_linux64/build/src/codegen.cpp:3616
emit_stmtpos at /buildworker/worker/package_linux64/build/src/codegen.cpp:3802 [inlined]
emit_function at /buildworker/worker/package_linux64/build/src/codegen.cpp:6255
jl_compile_linfo at /buildworker/worker/package_linux64/build/src/codegen.cpp:1160
emit_invoke at /buildworker/worker/package_linux64/build/src/codegen.cpp:3095
emit_expr at /buildworker/worker/package_linux64/build/src/codegen.cpp:3894
emit_ssaval_assign at /buildworker/worker/package_linux64/build/src/codegen.cpp:3616
emit_stmtpos at /buildworker/worker/package_linux64/build/src/codegen.cpp:3802 [inlined]
emit_function at /buildworker/worker/package_linux64/build/src/codegen.cpp:6255
jl_compile_linfo at /buildworker/worker/package_linux64/build/src/codegen.cpp:1160
emit_invoke at /buildworker/worker/package_linux64/build/src/codegen.cpp:3095
emit_expr at /buildworker/worker/package_linux64/build/src/codegen.cpp:3894
emit_ssaval_assign at /buildworker/worker/package_linux64/build/src/codegen.cpp:3616
emit_stmtpos at /buildworker/worker/package_linux64/build/src/codegen.cpp:3802 [inlined]
emit_function at /buildworker/worker/package_linux64/build/src/codegen.cpp:6255
jl_compile_linfo at /buildworker/worker/package_linux64/build/src/codegen.cpp:1160
emit_invoke at /buildworker/worker/package_linux64/build/src/codegen.cpp:3095
emit_expr at /buildworker/worker/package_linux64/build/src/codegen.cpp:3894
emit_ssaval_assign at /buildworker/worker/package_linux64/build/src/codegen.cpp:3616
emit_stmtpos at /buildworker/worker/package_linux64/build/src/codegen.cpp:3802 [inlined]
emit_function at /buildworker/worker/package_linux64/build/src/codegen.cpp:6255
jl_compile_linfo at /buildworker/worker/package_linux64/build/src/codegen.cpp:1160
emit_invoke at /buildworker/worker/package_linux64/build/src/codegen.cpp:3095
emit_expr at /buildworker/worker/package_linux64/build/src/codegen.cpp:3894
emit_ssaval_assign at /buildworker/worker/package_linux64/build/src/codegen.cpp:3616
emit_stmtpos at /buildworker/worker/package_linux64/build/src/codegen.cpp:3802 [inlined]
emit_function at /buildworker/worker/package_linux64/build/src/codegen.cpp:6255
jl_compile_linfo at /buildworker/worker/package_linux64/build/src/codegen.cpp:1160
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1794
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:825
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/builtins.c:633
eval at ./boot.jl:319 [inlined]
eval at /home/gary/.julia/packages/Reduce/sobXf/src/Reduce.jl:2 [inlined]
Load at /home/gary/.julia/packages/Reduce/sobXf/src/Reduce.jl:306
__init__ at /home/gary/.julia/packages/Reduce/sobXf/src/Reduce.jl:273
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1538 [inlined]
jl_module_run_initializer at /buildworker/worker/package_linux64/build/src/toplevel.c:90
jl_init_restored_modules at /buildworker/worker/package_linux64/build/src/dump.c:2413
_include_from_serialized at ./loading.jl:627
macro expansion at ./logging.jl:312 [inlined]
_require_search_from_serialized at ./loading.jl:698
_require at ./loading.jl:931
require at ./loading.jl:852
macro expansion at ./logging.jl:311 [inlined]
require at ./loading.jl:834
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1538 [inlined]
call_require at /buildworker/worker/package_linux64/build/src/toplevel.c:441 [inlined]
eval_import_path at /buildworker/worker/package_linux64/build/src/toplevel.c:476
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:663
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/builtins.c:633
eval at ./boot.jl:319
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
eval_user_input at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:85
macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:117 [inlined]
#28 at ./task.jl:262
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1538 [inlined]
start_task at /buildworker/worker/package_linux64/build/src/task.c:268
unknown function (ip: 0xffffffffffffffff)
Allocations: 13704922 (Pool: 13702141; Big: 2781); GC: 30
Segmentation fault (core dumped)

**Comment by KristofferC** [comment]
Seems like a Julia issue to me, perhaps it would be worth filing an issue against the Julia repo with reproducible steps?

**Comment by KristofferC** [comment]
Please comment if this keeps happening
