### ISSUE TITLE
Extra closing parenthesis when pasting code.

### ISSUE THREAD

**Issue by Ismael-VC** [KristofferC/OhMyREPL.jl#17]
Pasting something with parenthesis doesn't work correctly in v0.4.6 Windows and 0.6.0-dev.481 in Windows Subsystem for Linux (Ubuntu):

![image](https://cloud.githubusercontent.com/assets/4594825/18234570/05513792-72d0-11e6-9f9b-b1a6ca49f2ba.png)

![image](https://cloud.githubusercontent.com/assets/4594825/18234588/69191218-72d0-11e6-87f8-f6c46e45b246.png)

It works with this versions on CMD:

![image](https://cloud.githubusercontent.com/assets/4594825/18234595/935d38ce-72d0-11e6-8419-2915ec6dcffa.png)

![image](https://cloud.githubusercontent.com/assets/4594825/18234599/aed103ec-72d0-11e6-81a8-66223a07c8ae.png)

This doesn't happen with closing `}` or `]`.

**Comment by KristofferC** [comment]
Still true with `enable_autocomplete_brackets(false)`?

**Comment by Ismael-VC** [comment]
Indeed `enable_autocomplete_brackets(false)` fixes this issue, thank's again!

**Comment by KristofferC** [comment]
Well, disabling features doesn't really count as fixing :P Will look at it tonight.

**Comment by Ismael-VC** [comment]
You are right.

**Comment by okvs** [comment]
Is the following related? Tab-completion of dictionary string keys automatically adds `"]` after the key. If bracket autocompletion is on, this leads to a lot of `mydict["keyname"]"]`.

**Comment by KristofferC** [comment]
They seem to be related yes. It is weird though... I didn't expect the autocompletion to run a keybinding...
