### ISSUE TITLE
Adding custom colorschemes

### ISSUE THREAD

**Issue by okvs** [KristofferC/OhMyREPL.jl#18]
As far as I've been able to figure out, creating my own colorscheme involves directly hacking inside the file `SyntaxHighlighter.jl`.

It works, but, unfortunately also means I cannot update `PimpMyREPL` anymore :(

Is there planned any functionality for non-destructively adding ones own colorschemes? Or is there already some way?

**Comment by KristofferC** [comment]
No need to hack inside any files. You can run this after PimpMyREPL is loaded:

```jl
import PimpMyREPL.Passes.SyntaxHighlighter: ColorScheme, SYNTAX_HIGHLIGHTER_SETTINGS, add!
import PimpMyREPL.ANSICodes.ANSIToken

function _create_strange_colorscheme()
    strange = ColorScheme()
    strange.symbol = ANSIToken(foreground = rand(1:256))
    strange.comment = ANSIToken(foreground = rand(1:256))
    strange.string = ANSIToken(foreground = rand(1:256))
    strange.call = ANSIToken(foreground = rand(1:256))
    strange.op = ANSIToken(foreground = rand(1:256))
    strange.keyword = ANSIToken(foreground = rand(1:256))
    strange.text = ANSIToken(foreground = :default)
    strange._macro = ANSIToken(foreground = rand(1:256))
    strange.function_def = ANSIToken(foreground = rand(1:256))
    strange.error = ANSIToken(foreground = :default)
    strange.argdef = ANSIToken(foreground = rand(1:256))
    strange.number = ANSIToken(foreground = rand(1:256))
    return strange
end

add!(SYNTAX_HIGHLIGHTER_SETTINGS, "Strange", _create_strange_colorscheme())
```

![image](https://cloud.githubusercontent.com/assets/1282691/18257390/491c1700-73c3-11e6-87d9-7894eb562444.png)

But I should add proper documentation how to do this :) Will put it on my TODO list.

**Comment by okvs** [comment]
Oh, that is _excellent_!

**Comment by KristofferC** [comment]
Documented in https://kristofferc.github.io/OhMyREPL.jl/latest/features/syntax_highlighting.html#Creating-your-own-colorschemes.-1
