### ISSUE TITLE
1:m doesn't detect the colon as a range

### ISSUE THREAD

**Issue by MarcMush** [KristofferC/OhMyREPL.jl#181]
![Capture d’écran de 2019-08-26 13-49-32](https://user-images.githubusercontent.com/35898736/63688753-80efbf00-c808-11e9-8b87-689703ea130d.png)

**Comment by KristofferC** [comment]
This part needs to be fixed:

https://github.com/KristofferC/OhMyREPL.jl/blob/50f95e86e0ccfc9c9db7a077350bdd81a50813d0/src/passes/SyntaxHighlighter.jl#L112-L115

It is detecting `:m` as a symbol.
