### ISSUE TITLE
Save and set as default a new colorscheme

### ISSUE THREAD

**Issue by stefabat** [KristofferC/OhMyREPL.jl#185]
In the docs it's nicely explained how to create a color scheme, but it's not explained how to save it and set it as default (or at least I haven't seen it).

What's the best way here? I would like to avoid to redefine and set the scheme at every startup (i.e. in `startup.jl`), so I was considering to modify the package by myself and add a function `_create_ayu()` in `colorschemes.jl` and modify the remaining bits to have it as default. However this solution seems to much work for simply defining a new scheme and set it as default...

**Comment by KristofferC** [comment]
> I would like to avoid to redefine and set the scheme at every startup (i.e. in startup.jl),

That's what I would do. It's not really different from having a configuration file that is read on startup.

**Comment by stefabat** [comment]
All right, if that's the best option, I'm gonna go with that.
