### ISSUE TITLE
Backtick strings not correctly highlighted? 

### ISSUE THREAD

**Issue by ghyatzo** [KristofferC/OhMyREPL.jl#190]
Hello,

I noticed that while regular strings `"... stuff ..."` are correctly highlighted.
It is not the case when using backticks strings " `  " (help how do i code format a backtick??!?) to enclose shell/perl/ruby external commands.

Is this the intended behaviour? 
why not highlight it as a string? (or maybe differently. for example red to differentiate it from the standard string)

**Comment by KristofferC** [comment]
Probably just isn't implemented. Could be added to https://github.com/KristofferC/OhMyREPL.jl/blob/master/src/passes/SyntaxHighlighter.jl#L126. Seems like a good idea

**Comment by ghyatzo** [comment]
I can open a PR as soon as i wrap my head around the code

**Comment by KristofferC** [comment]
Fixed
