### ISSUE TITLE
Quotes and backticks not paired if immediately after another non brace character

### ISSUE THREAD

**Issue by ghyatzo** [KristofferC/OhMyREPL.jl#192]
Found the following undesired behaviour:
Using quotes or backtick immediately after another non whitespace character does not trigger the pairing.
While bracers work as expected: `c=(` correctly turns into `c=()`.

steps: 
```
c ="
c = r"
```
does not turn into `c=""` or `c = r""`.

curiosity: typing `c=("` works as expected returning `c=("")`

**Comment by KristofferC** [comment]
Fixed now.
