### ISSUE TITLE
Showing time in prompt

### ISSUE THREAD

**Issue by volkerkarle** [KristofferC/OhMyREPL.jl#197]
Hi there,
I wondered if something like

`OhMyREPL.input_prompt!(Dates.format(Dates.now(), "HH:MM:SS")*">", :green)`    

could be called dynamically such that my prompt shows the actual time? This would be very useful to have an idea about the run time of commands without the need of using a timer all the time.

Best,

v.

**Comment by KristofferC** [comment]
Sure, could you try with https://github.com/KristofferC/OhMyREPL.jl/pull/198

**Comment by volkerkarle** [comment]
That looks great! Thanks a lot!
