### ISSUE TITLE
no auto-complete single quotation mark immediately after letter

### ISSUE THREAD

**Issue by daviehh** [KristofferC/OhMyREPL.jl#200]
e.g. `a'` is used to Hermitian transpose a matrix/vector `a`. Right now, the single quotation mark `'` will auto complete to be a pair so typing a then ' gives `a''`. So, immediately after any letter sequence, is it better to leave the `'` alone? The double quotation mark is fine (a lone double quotation mark is not yet used and it's used for custom strings like v"1.3.0" so pairing for that is expected).

**Comment by ageron** [comment]
+1 and also after closing bracket, such as `[1 2 3]'`

**Comment by KristofferC** [comment]
IIRC, this used to be the case. Maybe https://github.com/KristofferC/OhMyREPL.jl/pull/193 changed it. Or maybe I misremember.

**Comment by KristofferC** [comment]
#202
