### ISSUE TITLE
Add fzf fuzzy search to REPL

### ISSUE THREAD

**Issue by Moelf** [KristofferC/OhMyREPL.jl#204]
Love using OhMyREPL, but I miss the `Ctrl-r` fuzzy search to find a command that is 10 lines away or yesterday, the original fzf package can be found [here](https://github.com/junegunn/fzf).

I already made [fzf_jll](https://github.com/JuliaBinaryWrappers/fzf_jll.jl) and a wrapper [module](https://github.com/Moelf/Fzf.jl) for it that can interactively search `repl_history.jl` (`inter_fzf(Fzf.read_repl_hist())`).

Wondering if this is a welcome enhancement, and if so where should I add this (key-binding / result substitution)

Thx!

**Comment by KristofferC** [comment]
That's a cool idea. I use fzf a lot as well. Not sure what the best keybinding is, perhaps it should just replace the defalt Ctrl+r?

**Comment by Moelf** [comment]
yeah, that's how fzf usually works in terminal emulators anyway, since it's strictly better (~100%) than default Ctrl+r I think it's appropriate to introduce it here

**Comment by Moelf** [comment]
ah ok, so I hacked together a working prototype: https://streamable.com/jxdjx9

setup:
```
]add JLFzf
``
then the following in `startup.jl`:
```
import REPL
import REPL.LineEdit
using JLFzf

const mykeys = Dict{Any,Any}(
    "^f" => function (s,o,c)
        b = JLFzf.read_repl_hist() |> inter_fzf;
        LineEdit.edit_insert(Base.active_repl.mistate, b)
    end,
)

function customize_keys(repl)
    repl.interface = REPL.setup_interface(repl; extra_repl_keymap = mykeys)
end

atreplinit(customize_keys)
```

**Comment by KristofferC** [comment]
Landed.
