### ISSUE TITLE
Colorful REPL

### ISSUE THREAD

**Issue by Cvikli** [KristofferC/OhMyREPL.jl#205]
Hey,

I was astonished by the styling of errors and colorization that was shown in the tutorial video. 
However whatever I try, I can't achieve the effects. 

Can anyone point to the right direction, how to modify the format and colorization?

**Comment by KristofferC** [comment]
You need to provide a bit more info. What did you do and what is not working?

**Comment by Cvikli** [comment]
I wanted to do the error colorization as shown in this video: https://youtu.be/lTLPAOLLbTU?t=577

Someone told me: "they removed it since the error messages for 0.5 significantly improved to 0.6"

But I still think this colorization could be beneficial. Not sure if it is still possible because I definitely think it could be improved and beneficial for a lot of people who develop a lot in julia?

**Comment by KristofferC** [comment]
Okay, yes that feature has been removed. However, in the upcoming 1.6 version of Julia, the errors have been improved.

![image](https://user-images.githubusercontent.com/1282691/91026522-22b41280-e5fb-11ea-896f-c6cda2264088.png)

**Comment by Cvikli** [comment]
That looks nice. 

Isn't it possible to customize it by time? 
Or can you help me how to do build our own image to customize these texts?

**Comment by KristofferC** [comment]
It is possible but not that easy. You can look how it was done in https://github.com/jkrumbiegel/ClearStacktrace.jl.
