### ISSUE TITLE
Potential rename of package, suggestions welcome.

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/OhMyREPL.jl#21]
The julia stewards mailed me that they didn't really like the name of this package (the pimp part). While I don't totally agree with them perhaps it is for the best to rename the package. I am having some troubles coming up with good ideas though.

What I want is a name that is a bit funny / non-serious while at the same time describes quite well what the package does. So It should be something with the REPL and something that it is being "pimped" (but not using this word of course) or "spiced up" etc. 

Any suggestions?

**Comment by okvs** [comment]
`REPLBling.jl`? It sounds better than it reads, though.

**Comment by Ismael-VC** [comment]
Just some thoughts:

* 
* REPLoid.jl
* REPLmania.jl
* EnhacedREPL.jl
* LiftedREPL.jl
* SpiceMyREPL.jl
* SuperREPL.jl
* 42.jl
* REPLReloaded.jl
* BeautifulREPL.jl
* AwesomeREPL.jl
* Delight.jl
* UberREPL.jl
* MyPrecious!.jl
* Majestic.jl
* OhMyREPL.jl
* BlingBling.jl
* BellsAndWhistles.jl

Some of them sounded *funny* (at least to me) when using them, ie. `using BellsAndWhistles` :smile_cat:

**Comment by okvs** [comment]
`PyntaMyREPL.jl`, unless that's to Swedish?

**Comment by Ismael-VC** [comment]
I guess it is, what does Pynta means?

**Comment by okvs** [comment]
It means decorate, spruce up, pimp, etc. etc. "Pynt" and "Pimp" sound a bit alike. But I wasn't being serious ;)

But anyway, `Spruce.jl`, `REPLjazz.jl`, `Fandangle.jl` (there's a word you don't hear alot..)

**Comment by KristofferC** [comment]
"Decorate" sort of.

**Comment by KristofferC** [comment]
OhMyREPL is pretty nice since there is an OhMyZsh that spices up the terminal. Thanks a lot for the suggestions.

**Comment by Ismael-VC** [comment]
`NinjaREPL.jl`, `Zen.jl`, `ZenREPL.jl`,

**Comment by okvs** [comment]
`REPLicious.jl`?

**Comment by KristofferC** [comment]
I will go with `OhMyREPL` :) Thanks @Ismael-VC. I will set the renaming in motion now. I want to keep the history of this repo so I will likely just rename it in place. This will cause breakage for users but hopefully not too many people are using this yet. I will put a big notice in the README as well :)
