### ISSUE TITLE
Remove space in output prompt

### ISSUE THREAD

**Issue by jakobnissen** [KristofferC/OhMyREPL.jl#211]
Currently, OhMyREPL inserts a space after your output prompt:
```
julia> 1
 1
^ triggered
```

This can't be removed, because OhMyREPL automatically places the space AFTER the user-defined prompt in [this line](https://github.com/KristofferC/OhMyREPL.jl/blob/85d5569717b8776e4351a91bf938b1296ed29d5b/src/output_prompt_overwrite.jl#L6).
The result is pretty annoying in many cases:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/23193950/91721185-a42a1880-eb98-11ea-93bb-4eb44a937949.png">
 
Or consider
```
julia> alignedseq
 ·······--··········· <-- alignment annotation doesn't match sequence :(
TAGCGTAGTAGCTAGTTAGC
```

So I propose just removing that space from the function and adding it to the default OUTPUT_PROMPT. Yes, users will have to add the space in their prompt. But at least we would be able to remove it.

**Comment by KristofferC** [comment]
Heh, yeah, makes sense to remove it.
