### ISSUE TITLE
Compatibility with vim-slime + tmux?

### ISSUE THREAD

**Issue by carlocab** [KristofferC/OhMyREPL.jl#224]
When I use [vim-slime](https://github.com/jpalardy/vim-slime) with tmux to send code to a Julia REPL, then I encounter the issue in #113. That is, trying to use slime to send code split over multiple lines doesn't work very well because OhMYREPL still seems to automatically close brackets for me.

I could probably get vim-slime to join lines with matching delimiters [before sending it to Julia](https://github.com/jpalardy/vim-slime#language-support), but I'd have to learn some more Vimscript first. (Or, figure out a way to do it in Python, but I don't really know much Python either.)

Is there a simpler way to fix this? 

It seems the issue is that slime uses tmux's paste buffer to send code to another pane, and tmux does not include the escape characters you mention in https://github.com/KristofferC/OhMyREPL.jl/issues/113#issuecomment-367291171. At least, that appears to have been the case when I used tmux's paste buffer directly to copy and paste code (rather than sending it through vim-slime).

**Comment by KristofferC** [comment]
Not sure, https://github.com/jpalardy/vim-slime/pull/205 suggests maybe it is fixed?

Maybe try https://github.com/jpalardy/vim-slime/issues/123#issuecomment-299616808.

**Comment by carlocab** [comment]
I'm not sure what's wrong, but it seems slime doesn't use bracketed paste by default in my installation.

However, I've checked that turning on bracketed paste should fix the problem (unless I'm missing something else), so I now know what I need to try to do. (And, thankfully, it's probably simpler than one of my initial ideas.)

Give me a little time to investigate this further, but I believe I should be able to close this issue.

Thanks for the help!

**Comment by carlocab** [comment]
Ok, this will be fixed in jpalardy/vim-slime#254. Not sure why that hasn't been merged yet, but I'll follow it up there.

Thanks again!

**Comment by ArbitRandomUser** [comment]
> I'm not sure what's wrong, but it seems slime doesn't use bracketed paste by default in my installation.
> 
> However, I've checked that turning on bracketed paste should fix the problem (unless I'm missing something else), so I now know what I need to try to do. (And, thankfully, it's probably simpler than one of my initial ideas.)
> 
> Give me a little time to investigate this further, but I believe I should be able to close this issue.
> 
> Thanks for the help!

how did you turn on bracketed paste mode , and where ? i'm having the same issue with kitty and tmux
