### ISSUE TITLE
Only "Monokai16" schema is working on windows

### ISSUE THREAD

**Issue by yongheekim-dev** [KristofferC/OhMyREPL.jl#225]
With julia 1.5.0 and windows machine only `Monokai16` is working for me

``` julia 
using OhMyREPL
for name in ("JuliaDefault", "Monokai16", "Monokai256", "Monokai24bit", "BoxyMonokai256", "TomorrowNightBright", "TomorrowNightBright24bit", "OneDark", "Base16MaterialDarker")
       test_colorscheme(name)
end
```
And I get 
![image](https://user-images.githubusercontent.com/42163454/93299744-83b4bc00-f830-11ea-8b3a-cd65b809ebf0.png)

**Comment by KristofferC** [comment]
If you use the nightly version of Julia together with Windows Terminal (https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) all of them should work.

**Comment by yongheekim-dev** [comment]
Yes all of schemas working with nightly build. Thank you
![image](https://user-images.githubusercontent.com/42163454/93301230-1bb3a500-f833-11ea-92c2-79e377288e12.png)
