### ISSUE TITLE
Makes Julia sluggish on exit

### ISSUE THREAD

**Issue by PallHaraldsson** [KristofferC/OhMyREPL.jl#228]
On my just compiled Julia master (for the first time):

```
$ ./julia --startup-file=no -q
julia> @time using OhMyREPL
  0.411028 seconds (347.56 k allocations: 24.408 MiB)

julia> CTRL-D
```

seems like 2 sec. to exit, enough that I pressed again (thinking it didn't take), and exited terminal too.

comparesd to immediate on Julia 1.5.1:
```
julia> @time using OhMyREPL
  0.588333 seconds (570.38 k allocations: 33.428 MiB, 1.51% gc time)
```

I also get a bit faster startup/fewer allocs on (but similar exit speed):

```
$ julia --startup-file=no
 _/ |\__'_|_|_|\__'_|  |  Commit a0a68a54d6 (12 days old master)

julia> @time using OhMyREPL
  0.368507 seconds (308.58 k allocations: 21.516 MiB)
```

I thought you would like to know, any idea how to debug this?

**Comment by KristofferC** [comment]
It's pretty fast for me. Does this only happen if the Ctrl D is the first thing you enter in the repl?

**Comment by PallHaraldsson** [comment]
CTRL-D (and what I show above) is the only thing I type. It very well may be a Julia thing, I thought I should still report here first.

It's about as slow in my first modified (second compiled) Julia, to exit, but my change regresses at least `using`

```
julia> @time using OhMyREPL
  0.969601 seconds (478.00 k allocations: 31.275 MiB)
```

I was changing Dict to OrderedDict. It indirectly changes e.g. WeakKeyDict (but not ImmutableDict).

**Comment by KristofferC** [comment]
It is probably that OhMyREPL needs some stuff compiled for the first REPL input. That's expected for now.
