### ISSUE TITLE
Highlight top-level file

### ISSUE THREAD

**Issue by dpsanders** [KristofferC/OhMyREPL.jl#24]
This is great! I was wondering if the top-level file could be highlighted, since that's usually (in my code / experience) where the problem lies?

**Comment by KristofferC** [comment]
We are talking about error messages I guess? How do you define "top-level file"? Last non Base file in the stacktrace?

**Comment by dpsanders** [comment]
Yes, sorry, error messages. I mean the file from my package which ran the code that produced the error. So yes, I guess that's what I mean.

**Comment by KristofferC** [comment]
> I mean the file from my package which ran the code that produced the error.

Can you be a bit more specific? What is available when the error is thrown is the backtrace up until that error and the error itself. In which file the bug actually exists seems hard to determine.

**Comment by KristofferC** [comment]
Closing in favour of https://github.com/JuliaLang/julia/issues/25375 since this package doesn't deal with Stacktraces anymore.
