### ISSUE TITLE
Characters slow to appear at first load

### ISSUE THREAD

**Issue by jebej** [KristofferC/OhMyREPL.jl#242]
The loading time of OhMyREPL is not too bad, but on my machine, entering characters for the first time is very slow.

Letters take a good 3-4 seconds to appear after typing them.

**Comment by KristofferC** [comment]
It's just standard compilation overhead. It could perhaps be lowered if we had a better API for the REPL to color text (so the method overwrites are not needed). An alternative is also to create a sysimage (https://julialang.github.io/PackageCompiler.jl/dev/examples/ohmyrepl/).

**Comment by jebej** [comment]
Could this be improved with a precompilation file?

**Comment by KristofferC** [comment]
Yes, probably.

**Comment by jtrakk** [comment]
Is there some code I can put in startup.jl that will make it compile the function at startup before I start typing?

**Comment by tfiers** [comment]
Oops, just found this issue now, after making https://github.com/KristofferC/OhMyREPL.jl/issues/286

@jtrakk @axsk, yes, see the `include("repl-trace-compile.jl")` I linked in that issue.
