### ISSUE TITLE
No highlighting when scrolling up through history on Julia 1.6

### ISSUE THREAD

**Issue by CameronBieganek** [KristofferC/OhMyREPL.jl#244]
On Julia 1.6, when I scroll up through the REPL history using the up arrow key, there is no syntax highlighting for the lines of code that are displayed. I double checked and on Julia 1.5 there is syntax highlighting when you scroll up through the REPL history.

One interesting thing to note is that the syntax highlighting re-appears if I scroll up with the up arrow key *and then* scroll to the left into the line of code with the left arrow key.

**Comment by KristofferC** [comment]
Fixed in https://github.com/KristofferC/OhMyREPL.jl/pull/298
