### ISSUE TITLE
OhMyREPL overwrites `active_repl`'s displaysize

### ISSUE THREAD

**Issue by jakobnissen** [KristofferC/OhMyREPL.jl#247]
When showing a large array, the default REPL fills the entire screen. I dislike that, and so I have this in my startup-file:

```julia
atreplinit() do repl
    repl.options.iocontext[:displaysize] = (24, displaysize(stdout)[2])
end
```

However, OhMyREPL seem to disable it, and setting the displaysize no longer has an effect after using OhMyREPL. Is ot possible for OhMyREPL to respect `:displaysize`?

**Comment by denius** [comment]
Also
```julia
julia> 1/pi
0.3183098861837907

julia> Base.active_repl.options.iocontext[:compact]=true
true

julia> 1/pi
0.31831
```

but after `OhMyREPL` loading
```julia
julia> using OhMyREPL

julia> 1/pi
0.3183098861837907

julia> Base.active_repl.options.iocontext[:compact]=true
true

julia> 1/pi
0.3183098861837907
```
via https://discourse.julialang.org/t/julia-for-scientists-summary-slides/91397/17

**Comment by KristofferC** [comment]
Seems to be fixed now.

**Comment by jakobnissen** [comment]
@KristofferC this still happens to me on Julia 1.9-rc1 with OhMyREPL 0.5.13. The two `startup.jl` files I compared were:
```
atreplinit() do repl
    repl.options.iocontext[:displaysize] = (24, displaysize(stdout)[2])
end
#using OhMyREPL
```
Versus the same file, but with OhMyREPL uncommented.

**Comment by KristofferC** [comment]
Yes, you probably need the new version I just released.

**Comment by jakobnissen** [comment]
Yes, you're right, it works when using OhMyREPL v0.5.14. Thank you for the fix!
