### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by dpsanders** [KristofferC/OhMyREPL.jl#25]
If I use the up arrow:
```
julia> if true
           println("hello")
       end
hello

julia> if true
hello      println("hello")
       end
julia>
```
Note where `hello` gets printed the second time when the cursor was at the end ofo `if true` after an up arrow.

**Comment by KristofferC** [comment]
Thanks, should be fixed by 3a9cd5e

**Comment by lstagner** [comment]
I think your fix broke the history autocomplete. You used to be able to type `x[uparrow]` to get the last command that started with `x`

**Comment by KristofferC** [comment]
Sorry.  Will fix it. I really need tests but it is difficult.

**Comment by KristofferC** [comment]
The fix didn't break it. It had been broken longer :)

**Comment by KristofferC** [comment]
@lstagner should be fixed now
