### ISSUE TITLE
`FzF` doesn't work for `julia-1.7-rc3` on MacOS

### ISSUE THREAD

**Issue by zfengg** [KristofferC/OhMyREPL.jl#252]
Below please find the screenshots.

<img width="1840" alt="Screenshot 2021-11-23 at 9 09 42 PM" src="https://user-images.githubusercontent.com/42152221/143030065-e2a29114-d02f-4af7-9cfc-bc8c680e50dc.png">

<img width="1840" alt="Screenshot 2021-11-23 at 9 10 32 PM" src="https://user-images.githubusercontent.com/42152221/143030110-6bd23015-819d-444f-8810-3df7d8dc67a6.png">

**Comment by KristofferC** [comment]
`fzf_jll` does not have a build for ARM on Mac.

**Comment by zfengg** [comment]
Hi, according to JuliaPackaging/Yggdrasil#3934, does it mean that it will only work on `julia1.6`? Sry I am not familiar with the technical details.

**Comment by Moelf** [comment]
@zfengg yes, because building for some platform only added after 1.6

**Comment by zfengg** [comment]
> @zfengg yes, because building for some platform only added after 1.6

Thanks a lot!
