### ISSUE TITLE
Dynamic prompt

### ISSUE THREAD

**Issue by eloualiche** [KristofferC/OhMyREPL.jl#260]
In the documentation I see that it seems possible to pass a function in the prompt. 

_"If the first argument instead is a function, it will be run every time the prompt wants to update which allows for more dynamic behavior."_

I have tried to have the time in the prompt as follows:

```julia
using Dates
OhMyREPL.input_prompt!(Dates.format(now(), "YYYYmmdd-HH:MM:SS> "), 13)
OhMyREPL.output_prompt!(Dates.format(now(), "YYYYmmdd-HH:MM:SS> "), 14)
```

<img width="238" alt="new_prompts_dynamic" src="https://user-images.githubusercontent.com/1526426/152614753-89c452af-80fa-4064-96a4-17f66ab57238.png">

The prompt does not seem to update the time and only considers the time when it has been updated.

**Comment by eloualiche** [comment]
I was made aware of a mistake in my initial issue (ht @matthieugomez).

I think what I was trying to achieve is similar to the following code in R:
```R
updatePrompt <- function(...) {options(prompt=paste0("|", format(Sys.time(), "%H:%M:%S"),"|R> ")); return(TRUE)}
addTaskCallback(updatePrompt)
```

The correct translation would probably to define a date function in the `input_prompt!` function:
```julia
using Dates
OhMyREPL.input_prompt!(x->Dates.format(now(), "YYYYmmdd-HH:MM:SS> "), 13)
OhMyREPL.output_prompt!(x->Dates.format(now(), "YYYYmmdd-HH:MM:SS> "), 14)
```

Unfortunately this code crashes Julia.

**Comment by Moelf** [comment]
```
julia> _m() = Dates.format(now(), "YYYYmmdd-HH:MM:SS> ")
_m (generic function with 1 method)

julia> OhMyREPL.input_prompt!(_m, 13)


20220206-15:18:26> 
```

not using an anonymous function fixes the crash

**Comment by matthieugomez** [comment]
Still, there should not be a crash right?

**Comment by Moelf** [comment]
yeah, PR is always welcomed of course. But since it's an easy workaround it's not a high priority I assume

**Comment by KristofferC** [comment]
This has nothing to do with anonymous functions. The function provided should take zero arguments but the example in https://github.com/KristofferC/OhMyREPL.jl/issues/260#issuecomment-1030904387 takes one argument. It should be:

```
using Dates
OhMyREPL.input_prompt!(()->Dates.format(now(), "YYYYmmdd-HH:MM:SS> "), 13)
OhMyREPL.output_prompt!(()->Dates.format(now(), "YYYYmmdd-HH:MM:SS> "), 14)
```

It looks like you will get a world age error one time when doing it like this. https://github.com/KristofferC/OhMyREPL.jl/pull/261 should fix that.
