### ISSUE TITLE
How can I type the matrix like this?

### ISSUE THREAD

**Issue by zdlspace0528** [KristofferC/OhMyREPL.jl#266]
Dear all,

I want to type the matrix like this.

'''A = [1 2 3
        4 5 6
        7 8 9]'''
But After I type the first line,I cannot type the second line?
What's wrong with this problem?

**Comment by Moelf** [comment]
after:
```
julia> A = [1 2 3<cursor here>
```
just hit enter?

**Comment by Moelf** [comment]
yes
