### ISSUE TITLE
No colors when using ctrl+p instead of up arrow

### ISSUE THREAD

**Issue by pwl** [KristofferC/OhMyREPL.jl#27]
I don't see any colors if I scroll through the previous commands using ctrl+p.  At the same time using up arrow seems to work fine.

**Comment by KristofferC** [comment]
Thanks, the way things are implemented right now is a bit like whack-a-mole.. I have to try think of a better way but it is difficult without monkey patching too much in Base.

**Comment by pwl** [comment]
Sorry but your patch didn't fix it for me.  Also there are no colors for reverse and forward search: ctrl+r and ctrl+s.

**Comment by pwl** [comment]
Maybe I should clarify what I mean by no colors.  The expressions are black when I hit ctrl+p repeatedly, but when I try to edit them, or just move the cursor the colors show up correctly.  So it's only the browsing of the expressions that doesn't seem to work.  Maybe it's not intended to work like I expect it to?

**Comment by KristofferC** [comment]
Yes `ctrl+r` and `ctrl+s` is not supported right now. Are you sure you updated? It didn't work for me before the patch and now it does:

![](https://media.giphy.com/media/l3vRaOTk7BmDxDwze/giphy.gif)

**Comment by pwl** [comment]
I forgot that I built OhMyREPL into the system image.  I recompiled it and now it works, thanks!

I haven't had much opportunity to test it but so far it looks like a great package.

**Comment by pwl** [comment]
There is still something off in this version.  The colors for ctrl+p/n show up correctly but only when I'm traversing the history in one direction.  For some expressions I see the right colors only when I'm going up (ctr+p) and some expressions behave the other way around, they are only colorized when I'm going down (ctrl+n).  When using arrow keys this effect disappears.

**Comment by KristofferC** [comment]
It would help if you could create a minimum working example. Basically a list of input to enter and keys to press. The Julia REPL has a quite a lot of different states and modes so it can be a bit tricky to reproduce.

**Comment by pwl** [comment]
From what I noticed it only bugs out with some old entries from my history, new entries seem to work fine.  Sorry for being vague, I will test it for a while and if the issue persists I will get back to you.  Thanks for the quick fix!
