### ISSUE TITLE
Right squre bracket

### ISSUE THREAD

**Issue by xijiang** [KristofferC/OhMyREPL.jl#285]
When typing the left bracket [, the right one ] appears. When typing ] again, an extra ] was there.
This behavior is different than typing (), or {}. When the right ones are overwritten. 
The extra ] results in often errors.
Can this be improved?
Many thanks.

**Comment by mbaz** [comment]
@xijiang See https://github.com/KristofferC/OhMyREPL.jl/issues/166

**Comment by KristofferC** [comment]
Should be fixed
