### ISSUE TITLE
Precompilation

### ISSUE THREAD

**Issue by tfiers** [KristofferC/OhMyREPL.jl#286]
Fantastic project.

When I load OhMyREPL ([here], in a macro in my startup.jl), I also run a list of precompile statements: https://github.com/tfiers/dotfiles/blob/main/.julia/config/repl-trace-compile.jl

That way, I don't get those jarring delays that normally occur after the first keystrokes and output prints, just after OMR is loaded.

Would it be an idea to add such precompilation of real-world-usage¹ to OMR itself?
Using https://timholy.github.io/SnoopCompile.jl/stable/snoop_pc/, probably

[here]: https://github.com/tfiers/dotfiles/blob/174862c/.julia/config/startup.jl#L44

¹ <sub>Main usage thing still missing from the repl-trace I linked: fzf history search</sub>

**Comment by tfiers** [comment]
Just found #242, where the [package author seems open][ref] to adding this.

Might open a PR if I have some time; or if anyone else want to give it a go based on what I linked above, feel free

[ref]: https://github.com/KristofferC/OhMyREPL.jl/issues/242#issuecomment-872993564

**Comment by KristofferC** [comment]
Fixed in https://github.com/KristofferC/OhMyREPL.jl/pull/296
