### ISSUE TITLE
Plans for improvements

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/OhMyREPL.jl#30]
Each pass now assigns an `ANSIToken` to each Julia token from `Tokenize.jl`. This means that the coloring is coupled tightly to the tokenizer which does not work well for other REPL modes like Cxx.jll. Instead, each pass could assign an `ANSIToken` to a range of character indices which would decouple the tokenization from the coloring. `Tokenize.jl` would then just be a help module for the syntaxhighlighter. Each pass could then also decide what mode it wants to be active in so the Julia highlighter mode is only active when the Julia REPL is active. Need to figure out how to deal with the different search modes in the REPL though.

Concrete steps:
- [ ] Change to a character range colorization. Need to figure out how to deal with partly overlapping ranges though `[---bold + red -{---]--green}` Can no longer just print a `ResetToken` in the end of the range. Update: Probably solved by printing a `ResetToken` at each transition and then printing the merged `ANSIToken` from all the active tokens in an overlapping range.
- [ ] Make each pass be able to register to a specific mode. Or alternatively, each mode can register with a different pass. Some passes can default be on for everything (bracket highlighter).

**Comment by musm** [comment]
This may make your life easier: https://blogs.msdn.microsoft.com/commandline/2016/09/22/24-bit-color-in-the-windows-console/   💯

**Comment by KristofferC** [comment]
Cool stuff!

**Comment by KristofferC** [comment]
Probably won't happen
