### ISSUE TITLE
Red background for --

### ISSUE THREAD

**Issue by albheim** [KristofferC/OhMyREPL.jl#310]
Since some recent update it seems like `--` gets a red background, 

![image](https://user-images.githubusercontent.com/3112674/226550157-338c1cf8-642b-4522-b137-f20fed1a557c.png)

I find it mostly ugly in the cases I have used it (e.g.  pkg mode `activate --temp`). 

No big deal, just unclear to me why this is. Found #309 which seems maybe related since it is about red background, but haven't looked into it to see if it should affect this case.

**Comment by KristofferC** [comment]
It should be disabled in Pkg mode. For julia code I think it makes sense since it is invalid syntax.

**Comment by albheim** [comment]
Okay, I agree it can make sense with julia mode.
Should have posted the case I actually ran into instead of what I thought was a more basic one :sweat_smile: this is with Julia 1.9 rc1 and OhMyREPL v0.5.19, started with `--startup-file=no`
![image](https://user-images.githubusercontent.com/3112674/226601944-7ab8a690-2148-4f74-82ca-18d1c885921d.png)
