### ISSUE TITLE
Indentation of continuation lines broken when using non-standard input prompt

### ISSUE THREAD

**Issue by mgkurtz** [KristofferC/OhMyREPL.jl#315]
Using a custom input prompt, multi-line input is shown misaligned, but the cursor is at the position, where it should be, if all were well-aligned. This turns me quite mad :face_with_spiral_eyes:
```julia
julia> OhMyREPL.input_prompt!("∴> ")

∴> """
   █   abc
       """
```
The `█` depicts where the cursor appears, when it is at the beginning of the second line, i.e. where a `<Delete>` will delete the `a`.

According to `git bisect` this bug was introduced with 1bc0e5b7ec9e1a9b294e0ffc5ff651a2294a69e1. Before that, I got
```julia
julia> OhMyREPL.input_prompt!("∴> ")

∴> """
   abc
   """
```
with cursor and display aligning correctly.

The bug appears with prompts of all lengths, but the default one.

**Comment by KristofferC** [comment]
Thanks for the report and the bisect. I'll try figure out where the divergence between the old tokenizer and the new one is.

**Comment by dhanak** [comment]
This only occurs with Julia 1.8, older versions work as expected.

**Comment by dhanak** [comment]
I confirm that this is broken. Downgrading OhMyREPL to v0.5.17 solves the issue.

(Also note that v0.5.18 is broken, it doesn't compile.)

**Comment by KristofferC** [comment]
I'm guessing https://github.com/KristofferC/OhMyREPL.jl/issues/313 is a dup of this then.
