### ISSUE TITLE
Noticeable lag when importing with ProgressLogging.jl

### ISSUE THREAD

**Issue by mkschleg** [KristofferC/OhMyREPL.jl#316]
I'm noticing that there is considerable lag in the REPL when importing OhMyREPL.jl and ProgressLogging.jl on julia 1.9-rc1. The lag isn't in import, but the REPL hangs quite a bit after the second package is loaded (it doesn't matter which order). 

Using:
```
ProgressLogging v0.1.4
OhMyREPL v0.5.20
```

**Comment by jakobnissen** [comment]
I see 136 invalidations in JuliaSyntax when loading `ProgressLogging` and 493 invalidations total, compared to 356 invalidations total when not loading OhMyREPL. I also experience this myself when loading JSON3. Unfortunately, https://github.com/timholy/SnoopCompile.jl/issues/354 prevents me from finding the source.

But it seems that JuliaSyntax (and hence OhMyREPL) is prone to invalidations and will cause the REPL to hang if that happens.

**Comment by mkschleg** [comment]
Seems to be fixed in RC2. So I'm closing.
