### ISSUE TITLE
Julia crashes if OhMyREPL in .juliarc.jl but not installed

### ISSUE THREAD

**Issue by dpsanders** [KristofferC/OhMyREPL.jl#32]
With `using OhMyREPL` in `.juliarc.jl`, but the package not installed, Julia 0.6-dev exits with nothing printed. (I realise this is not actually a bug with this package...)

Previously there was a little script available that checked if OhMyREPL.jl was installed, but I can't seem to find it any more.

**Comment by Ismael-VC** [comment]
According to this late version:

* https://github.com/KristofferC/OhMyREPL.jl/blob/6a23713bd75b8b34ba3667f7844d17452adcb97b/README.md

It could be something like:

```julia
function setup()
    if isdir(Pkg.dir("OhMyREPL"))
        @async @eval using OhMyREPL
    else
        warn("OhMyREPL not installed")
    end
end

setup()
```

I haven't tested, I'm on cellphone.

**Comment by KristofferC** [comment]
Yeah should probably add that back.

**Comment by KristofferC** [comment]
Why is the async eval stuff needed. Just `using` seems to also work?

**Comment by Ismael-VC** [comment]
Yes it is a vestigial remnant of the last version of that snippet, it works without it.

**Comment by mindbound** [comment]
It doesn't seem to work without the `@eval` part, at least on Julia v0.5.0 - fails with

> ERROR: LoadError: error compiling setup: unsupported or misplaced expression "using" in function setup

**Comment by Ismael-VC** [comment]
@mindbound and @KristofferC I mean  that `@async` **is not** strictly needed, but `@eval` **is** needed indeed. Try this instead:

```julia
function oh_my_repl()
    if isdir(Pkg.dir("OhMyREPL"))
        @eval using OhMyREPL
    else
        warn("OhMyREPL not installed")
    end
end

oh_my_repl()
```

**Comment by KristofferC** [comment]
My point is that it works without the @eval if you dont put it in a function.

**Comment by mindbound** [comment]
Thank you, without `@async` everything works as far as my previous comment is concerned.
