### ISSUE TITLE
`$TERM` supports 256 colors, but don't have colors

### ISSUE THREAD

**Issue by chriselrod** [KristofferC/OhMyREPL.jl#333]
If I start Julia with
```
> TERM=xterm-256color julia
```
I do get colors, but not when using my default `$TERM` value (`foot`, for reference).
```
> infocmp $TERM | grep color
	colors#0x100, cols#80, it#8, lines#24, pairs#0x10000,
> infocmp xterm-256color | grep color
#	Reconstructed via infocmp from file: /usr/share/terminfo/x/xterm-256color
xterm-256color|xterm with 256 colors,
	colors#0x100, cols#80, it#8, lines#24, pairs#0x10000,
> infocmp xterm | grep color
	colors#8, cols#80, it#8, lines#24, pairs#64,
```
My `terminfo` does indeed say that I have `colors#0x100` (`0x100==256`), just like it does for `xterm-256color`.

**Comment by Moelf** [comment]
idk why I am seeing color
![image](https://github.com/KristofferC/OhMyREPL.jl/assets/5306213/77eb0248-7769-4771-b347-bbfc891df7f8)

**Comment by chriselrod** [comment]
> So this only happens with OhMyREPL loaded? Could maybe be related to https://github.com/JuliaLang/julia/pull/50797?

Yeah, that seems likely to be the cause.
My problem is unrelated to OhMyREPL.

```julia
julia> for i = 0:255; printstyled("$i\t";color=i); i%16==0&&println(); end
```
No color, not even on Julia, when starting with `--startup=no`.
Any chance you can try Julia master, @Moelf ? I'm guessing that PR didn't make it into 1.10.

**Comment by Moelf** [comment]
![image](https://github.com/KristofferC/OhMyREPL.jl/assets/5306213/9736c4ff-18cd-4021-a653-a0e32245aa88)

still seems fine on master

**Comment by chriselrod** [comment]
Hmm
```julia
julia> Base.find_terminfo_file("foot")

julia> Base.find_terminfo_file("xterm")

julia>
```
