### ISSUE TITLE
Donot work when julia binary runs with command-line arguments. causing issue is repl in emacs julai-snail package

### ISSUE THREAD

**Issue by Aneeqasif** [KristofferC/OhMyREPL.jl#337]
Hi there, Due to this restriction users of julia-snail in emacs cannot use this package. Please address this issue
**Reference :** 
 https://github.com/gcv/julia-snail/issues/140

**Comment by Moelf** [comment]
"command-line running a file" is distinctively not REPL, I would hope julia-snail to find a solution to load themselves properly to indicate they're operate Julia interactively

**Comment by gcv** [comment]
> "command-line running a file" is distinctively not REPL

Why not? Given a file `sample.jl` with the following code:

```julia
function f(x)
   x
end
```

I can then run `julia -L sample.jl` which starts a normal, interactive Julia REPL, which just happens to have loaded the file `sample.jl` first.

**Comment by Moelf** [comment]
you should use `-i`

**Comment by gcv** [comment]
Thanks, that seems to work as expected.

**Comment by gcv** [comment]
@Aneeqasif, this ticket can probably be closed.
