### ISSUE TITLE
Prefix `julia>` in online examples is not understood

### ISSUE THREAD

**Issue by juliohm** [KristofferC/OhMyREPL.jl#344]
For instance, consider the GR examples:

```julia
julia> # Create example point data
julia> x = 8 .* rand(100) .- 4
julia> y = 8 .* rand(100) .- 4
julia> z = sin.(x) .+ cos.(y)
julia> # Draw the contour plot
julia> contour(x, y, z)
julia> # Create example grid data
julia> x = LinRange(-2, 2, 40)
julia> y = LinRange(0, pi, 20)
julia> z = sin.(x') .+ cos.(y)
julia> # Draw the contour plot
julia> contour(x, y, z)
julia> # Draw the contour plot using a callable
julia> contour(x, y, (x,y) -> sin(x) + cos(y))
```

In previous versions, we could simply copy/paste the example as is. Now we get an error:

```julia
ERROR: UndefVarError: `julia` not defined
```

**Comment by KristofferC** [comment]
> In previous versions, we could simply copy/paste the example as is.

What version?

I've been trying to copy paste this back to Julia 1.8 without OhMyREPL and it doesn't work:

**Comment by juliohm** [comment]
I don't recall the version of Julia + OhMyREPL.jl, but I remember this used to work, not sure.

**Comment by KristofferC** [comment]
> but I remember this used to work, not sure.

Went back to Julia 1.0 and still doesn't work without OhMyREPL.jl at least.
