### ISSUE TITLE
Redundant quotation mark `"` in tab completion of paths

### ISSUE THREAD

**Issue by adomasbaliuka** [KristofferC/OhMyREPL.jl#348]
Suppose I have a file in the current working directory named "somefile.txt" 

When NOT using OhMyREPL, if I type
```julia
julia> open("./s
```
and then type TAB, the completion gives me (which is good!)
```julia
julia> open("./somefile.txt"
```

However, when USING OhMyREP, typing the first `"` character inside `open("./s` automatically writes the "closing" second `"` character (and also a closing `)` but that doesn't matter here). When invoking the tab completion, *another* `"` character is produced, resulting in 
```julia
julia> open("./somefile.txt"")
```

I then have to delete the extra `"`.

### System Info
```
  [5fb14364] OhMyREPL v0.5.24

Julia Version 1.10.4
Commit 48d4fd48430 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
```

**Comment by axsk** [comment]
c.f. https://github.com/KristofferC/OhMyREPL.jl/issues/334

**Comment by dhanak** [comment]
A quick fix for this is to add the following to your `startup.jl` (in the function called by `atreplinit()`):

```julia
    # quickfix for path completion issue (don't add closing quotes)
    @eval REPL.REPLCompletions close_path_completion(d, ps, s, p) = false
```
