### ISSUE TITLE
Endless precompiling in `v1.12.0-DEV`

### ISSUE THREAD

**Issue by huangyxi** [KristofferC/OhMyREPL.jl#351]
`]add OhMyREPL` seems to hang in `v1.12.0-DEV`.

```julia
julia> versioninfo()
Julia Version 1.12.0-DEV.789
Commit 45641340cc1 (2024-06-27 04:03 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 256 × AMD EPYC 7763 64-Core Processor
  WORD_SIZE: 64
  LLVM: libLLVM-17.0.6 (ORCJIT, znver3)
Threads: 1 default, 0 interactive, 1 GC (on 256 virtual cores)
```

I have checked that the precompiling process is hanging at this line: https://github.com/KristofferC/OhMyREPL.jl/blob/b0071f5ee785a81ca1e69a561586ff270b4dc2bb/src/precompile.jl#L87
However, I lack PTY-related knowledge and hope someone can fix it.

**Comment by KristofferC** [comment]
Thanks for the report. I don't have too much time looking into this right now but will probably get to it at some point unless someone beats me to it.

**Comment by duzaichuan** [comment]
v1.11.0 rc2 seems also have this issue. Did not manage to precompile.

**Comment by singularitti** [comment]
Same here!

```julia
julia> versioninfo()
Julia Version 1.11.0-rc2
Commit 34c3a63147b (2024-07-29 06:24 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, apple-m1)
Threads: 8 default, 0 interactive, 4 GC (on 8 virtual cores)
```

**Comment by KristofferC** [comment]
Should be fixed
