### ISSUE TITLE
Latest version prints "type Nothing has no field interface" when loaded in startup.jl.

### ISSUE THREAD

**Issue by lassepe** [KristofferC/OhMyREPL.jl#354]
Withe the startup.jl

```julia
if Base.isinteractive()
    @eval Main using OhMyREPL: OhMyREPL
end
```

OhMyREPL prints "type Nothing has no field interface" below the banner:

![image](https://github.com/KristofferC/OhMyREPL.jl/assets/10076790/191d40d8-b522-4268-a9eb-775a7f2a9aa8)

Interestingly, when loaded manually (after `startup.jl`) in the otherwise same way, this does not happen:

![image](https://github.com/KristofferC/OhMyREPL.jl/assets/10076790/de92c2bc-c2b3-4eed-bd28-aff8c6206202)

**Comment by KristofferC** [comment]
Should be fixed by https://github.com/KristofferC/OhMyREPL.jl/pull/353

**Comment by lassepe** [comment]
You are right. I just double checked and the issue is indeed gone on `master`. Thanks! Sorry for the noise.
