### ISSUE TITLE
Significant input lag after `using InlineStrings`

### ISSUE THREAD

**Issue by carstenbauer** [KristofferC/OhMyREPL.jl#361]
```julia
julia> using InlineStrings

julia> # typing something has significant input lag (when OhMyREPL.jl is loaded)
```

(I opened an issue here because it's OhMyREPL that's at work while typing things.)

Came up over in JuliaCon.jl (https://github.com/JuliaCon/JuliaCon.jl/issues/37).

cc: @quinnj

**Comment by Moelf** [comment]
maybe same underlying cause as #355 ? Namely type piracy?

**Comment by KristofferC** [comment]
Not type piracy but invalidatiokns. https://github.com/JuliaStrings/InlineStrings.jl/pull/77 fixes this.

**Comment by KristofferC** [comment]
Should be fixed now
