### ISSUE TITLE
REPL Search History not working with Julia 1.10.4

### ISSUE THREAD

**Issue by PGS62** [KristofferC/OhMyREPL.jl#362]
With Julia 1.10.4 and OhMyREPL 0.5.27 when I hit Ctrl+R, I see recent commands but hitting enter does not recall the currently selected line (and the `julia>` prompt disappears). Things work correctly with Julia 1.9.4 and OhMyREPL 0.5.27.

This is on Windows, but I've also seen the same issue on MacOS with Julia 1.7 and OhMyREPL 0.5.27 and on Ubuntu under WSL2 with Julia 1.10.4 and OhMyREPL 0.5.27, so I don't think it's a Windows-only issue.

I didn't realise how much I liked search history until I had to do without it!

**Comment by disberd** [comment]
I have also noticed this on my windows machine after updating to 0.5.27.
I just tried reverting to v0.5.24 and the issue disappears also in v1.10.4, so it only seems broken on latest OhMyREPL for 1.10.4

**Comment by roflmaostc** [comment]
I observe the same on Linux and 1.10.4

**Comment by sandyspiers** [comment]
I've noticed the same thing.

It looks like it might have been introduced in #347.
Dropping this commit locally fixes the issue for me.
