### ISSUE TITLE
OhMyREPL precompiles forever on 1.11.0-rc3

### ISSUE THREAD

**Issue by gdalle** [KristofferC/OhMyREPL.jl#371]
I can't even enter any code because the precompilation literally doesn't stop (> 1 min).
Has anyone else encountered the issue?

**Comment by KristofferC** [comment]
What version?

**Comment by gdalle** [comment]
Sorry I hadn't seen the closed issues. I guess it must have been an old version, I updated OhMyREPL and it works now
