### ISSUE TITLE
Register OhMyREPL as an official package.

### ISSUE THREAD

**Issue by Ismael-VC** [KristofferC/OhMyREPL.jl#44]
This would also need to register Tokenize.jl

Currently I have to do something like:

```julia
julia> repositories = [
           "https://github.com/KristofferC/Tokenize.jl",
           "https://github.com/KristofferC/OhMyREPL.jl",
           "https://github.com/Ismael-VC/JuliaRC.jl"
       ];

julia> foreach(Pkg.clone, repositories)                                                                                   
INFO: Initializing package repository /home/juser/.julia/v0.5                                                             
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
INFO: Cloning Tokenize from https://github.com/KristofferC/Tokenize.jl
INFO: Computing changes...
INFO: Cloning cache of Compat from https://github.com/JuliaLang/Compat.jl.git
INFO: Installing Compat v0.9.5
INFO: Package database updated
INFO: Cloning OhMyREPL from https://github.com/KristofferC/OhMyREPL.jl
INFO: Computing changes...
INFO: Cloning cache of BaseTestNext from https://github.com/JuliaCI/BaseTestNext.jl.git
INFO: Installing BaseTestNext v0.2.2
INFO: Cloning JuliaRC from https://github.com/Ismael-VC/JuliaRC.jl
INFO: Computing changes...
INFO: No packages to install, update or remove                                                                            

julia>       
```

In order to install my personal package [JuliaRC.jl](https://github.com/Ismael-VC/JuliaRC.jl) which basically is a refactor of my monolithic `~/.juliarc.jl`, I need to remember to clone both `Tokenize` and `OhMyREPL`. 

This package has already ~50 starts and a bunch of forks, as @KristofferC has stated, not all of this package functionality may be able to get into base soon or at all, which is why I ask for this package to be registered officially, so I can add it to my `REQUIRE` file for easy install, I can see other people benefit by this move also.

It may even be worthwhile to consider creating a **JuliaTooling** organization or something like that, in order to aid centralize tooling efforts.

**Comment by KristofferC** [comment]
Done
