### ISSUE TITLE
Error with enable_autocomplete_brackets in juliarc.jl

### ISSUE THREAD

**Issue by EthanAnderes** [KristofferC/OhMyREPL.jl#50]
I'm having trouble getting OhMyREPL to work in Julia v0.6. I get the following error when starting the REPL:

```
julia> ERROR (unhandled task failure): MethodError: no method matching enable_autocomplete_brackets(::Bool)
The applicable method may be too new: running in world age 21291, while current world is 21317.
Closest candidates are:
  enable_autocomplete_brackets(::Bool) at /Users/ethananderes/.julia/v0.6/OhMyREPL/src/BracketInserter.jl:36 (method too new to be called from this world context.)
 in macro expansion at .juliarc.jl:12 [inlined]
 in uERROR (unhandled task failure): type UnionAll has no field name
ERROR (unhandled task failure): type UnionAll has no field name
```

I have the following in my `.juliarc.jl` file which may be causing the problem. If I remove it, then type `using OhMyREPL` at the repl there is no error

```
function setup()
    if isdir(Pkg.dir("OhMyREPL"))
        @async while true
            if isdefined(Base, :active_repl)
                @eval using OhMyREPL
                OhMyREPL.BracketInserter.enable_autocomplete_brackets(false)
                break
            else
                sleep(0.1)
            end
        end
    else
        warn("OhMyREPL not installed")
    end
end
setup()
```

**Comment by KristofferC** [comment]
Interesting, it might be because it is inside an `@async`. What happens if you just have 

```jl
using OhMyREPL
OhMyREPL.BracketInserter.enable_autocomplete_brackets(false)
```

in the `.juliarc.jl`?

**Comment by EthanAnderes** [comment]
Yep, that seems to work fine...and now that I think of it, I'm not sure why I had the more complicated version in my `.juliarc.jl` to begin with. I suspect it was to avoid errors when using older versions of Julia on my machine that didn't have OhMyRepl installed. 

Feel free to close this issue since the problem seems solved for me. Thanks for looking into it.
