### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/OhMyREPL.jl#59]
There is some small flickers sometimes when holding a key (worse on Windows).

Right now, the whole terminal buffer is rewritten from scratch at every keystroke. Instead, I should keep two buffers, one with the raw text and one with the colored text and only write the diff from the last keystroke to the terminal buffer.

**Comment by mkborregaard** [comment]
The flickers are very noticeable on my Mac at the moment, which I did not notice before. I came to open an issue for that, as it somewhat lessens the enjoyment of using the package.

**Comment by KristofferC** [comment]
Yeah, it is unfortunate. I don't have a clear way of how to implement this now and there will be some time before I can properly debug-test things for this.

**Comment by mkborregaard** [comment]
It will definitely be appreciated whenever it does happen :-)

**Comment by KristofferC** [comment]
It would be helpful if you could try out #86 and report back.

**Comment by mkborregaard** [comment]
I've been on holiday and am only back now - but it works :-) Back to my beautiful colored REPL! Thanks!

**Comment by mkborregaard** [comment]
This can be closed IMHO

**Comment by KristofferC** [comment]
Indeed!

**Comment by mkborregaard** [comment]
This package is awesome, just saying.

**Comment by KristofferC** [comment]
<3
