### ISSUE TITLE
repl hangs after input `1e1`

### ISSUE THREAD

**Issue by EthanAnderes** [KristofferC/OhMyREPL.jl#60]
The latest master hangs when I try to enter `1e1` and becomes unresponsive to cntr-c. E.g.

```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-pre.alpha.150 (2017-03-16 05:46 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 102800a (1 day old master)
|__/                   |  x86_64-apple-darwin16.4.0

julia> 1e1
10.0

julia> using OhMyREPL


```

you can't see the last entry since it disappears at the point `julia> 1e`.

**Comment by pkofod** [comment]
I had something like this happening earlier as well. Typed in something (can't remember what) and the `julia> ` disappeared, and everything froze. This was on v0.5 though

**Comment by KristofferC** [comment]
Thanks, there have been some updates to Tokenize.jl to fix things for https://github.com/ZacLN/Parser.jl and it seems to have some bugs. I'll try fix it tomorrow. CC @ZacLN.

**Comment by EthanAnderes** [comment]
Awesome. Thanks!

**Comment by KristofferC** [comment]
One of the problems with not having the package registered is that everyone gets on the master branch of the dependencies.

**Comment by KristofferC** [comment]
Actually, I fixed it now https://github.com/KristofferC/Tokenize.jl/pull/79:

Hopefully, the more accurate syntax highlighter is worth the troubles:

![image](https://cloud.githubusercontent.com/assets/1282691/24065553/3da0da28-0b6c-11e7-86f9-df5bc0d00330.png)
