### ISSUE TITLE
RGB codes of the ANSI color scheme

### ISSUE THREAD

**Issue by mkborregaard** [KristofferC/OhMyREPL.jl#63]
Is there an easy way to get the RGB (or hex) codes for the color numbers from `ANSICodes.test_ANSI_256()`?

**Comment by KristofferC** [comment]
I found this table: http://www.calmar.ws/vim/256-xterm-24bit-rgb-color-chart.html. Would be nice to have a small script for it though.

**Comment by mkborregaard** [comment]
Thanks! Yes I thought (briefly) about making a method for ANSIToken that took any valid Julia Color and picked the closest in RGB space.

**Comment by KristofferC** [comment]
For RGB -> 256 I use https://gist.github.com/MicahElliott/719710

**Comment by mkborregaard** [comment]
Fantastic!

**Comment by mkborregaard** [comment]
Here is a Julian version - it depends on Colors so you probably don't want it in the package:
https://gist.github.com/mkborregaard/06ed2a3d2c23322449acb7f947bda444

**Comment by mkborregaard** [comment]
@KristofferC there appears to be a discrepancy between the colors in those tables and the ones shown by `test_ANSI_256()` for the first 16 colors, at least on my Mac. Compare
<img width="560" alt="skaermbillede 2017-04-27 kl 10 16 00" src="https://cloud.githubusercontent.com/assets/8429802/25475298/9b914b9c-2b36-11e7-9912-232c12eea1d3.png">
with
<img width="384" alt="skaermbillede 2017-04-27 kl 10 16 48" src="https://cloud.githubusercontent.com/assets/8429802/25475311/a3b29132-2b36-11e7-8753-37d45b320b52.png">
For instance, the red color, `1` in `test_ANSI_256()` corresponds to `9` in the xterm color chart. According to both sources, the code for `9` should be "#ff0000", the same color as `196`, but in `test_ANSI_256()` it is `1` that has this color. So it looks like something is amiss with OhMyREPL's colors for the first 16. I have updated the function in the gist to simply ignore the first 16 numbers so that should work fine, but I'll just reopen the issue to flag this.

**Comment by KristofferC** [comment]
Can you try the following in your terminal:

```
using Crayons
for j in [1, 9, 196] println(Crayon(foreground = j)("█"^50)); end
```

With default settings in gnome-terminal I get

![image](https://cloud.githubusercontent.com/assets/1282691/25481734/d106ca00-2b4e-11e7-9eaa-3ed9018c5355.png)

which means that 9 and 196 is the same color?

**Comment by mkborregaard** [comment]
![skaermbillede 2017-04-27 kl 14 21 46](https://cloud.githubusercontent.com/assets/8429802/25483138/e18c99e4-2b54-11e7-8ad9-b32d16dc9ca0.png)
I wonder if this is OS-specific.

**Comment by KristofferC** [comment]
The 16 base colors can be set by themes, see for example https://terminal.sexy/. Perhaps the terminal you are using do not have the default settings (or the default settings are different).

**Comment by mkborregaard** [comment]
Yes, it's possible. Unfortunately the inbuilt terminal app on my Mac appears to have died with the last OS update. There still seems to be an inconsistency between your results in gnome-terminal and those in  https://gist.github.com/MicahElliott/719710 and http://www.calmar.ws/vim/256-xterm-24bit-rgb-color-chart.html, though?

**Comment by KristofferC** [comment]
In gnome-terminal, 9 and 196 has the same color which is what the chart showed?

**Comment by mkborregaard** [comment]
Oh yeah that's right, my bad. Sorry.

**Comment by KristofferC** [comment]
Latest 0.6 version supports 24-bit rgb now

**Comment by mkborregaard** [comment]
I guess I should update the TomorrowNightBright colors then?

**Comment by KristofferC** [comment]
If you feel like it you could add a 24 but version. But only if you want :)
