### ISSUE TITLE
Loading OhMyREPL for interactive sessions only

### ISSUE THREAD

**Issue by joshbode** [KristofferC/OhMyREPL.jl#68]
Since `isinteractive() == false` when run from `.juliarc.jl` (even for interactive sessions - possibly a bug in Julia?), in order to load OhMyREPL for interactive sessions only, I have the following in my `.juliarc.jl` file:

```julia
# .juliarc.jl
let
    # program
    if !isempty(ARGS) && !isempty(first(ARGS))
        return
    end
    options = Base.JLOptions()
    # command-line
    if (options.eval != C_NULL) || (options.print != C_NULL)
        return
    end
    import OhMyREPL
end
```

Would something like this be useful in the package itself? Or is there an easier way?

**Comment by tkelman** [comment]
this would be valuable to avoid having the methods this package overwrites change the behavior of any other code (printing of errors in tests for example)

**Comment by joshbode** [comment]
That was my thinking, plus to (marginally) reduce load time for non-interactive scripts that don't need REPL magic.

Is it a bug that `isinteractive()` is `false` for interactive sessions when evaluated at the point at which `.juliarc.jl` is being loaded, though? Or is it understood that `isinteractive` is only useful once you're at the REPL (which seems to defeat the purpose of it)?

**Comment by chriselrod** [comment]
Any updates? It's a lot more important now that we have Pkg3.
I tried using
```julia
if Base.JLOptions().check_bounds != 1 # Hack so that this is not run while testing packages.
        using OhMyREPL
end
```
so that it doesn't try to run `OhMyREPL` while testing packages.

Unfortunately, I don't know how to NOT put projects I'm working on in separate environments from the primary `(0.7)` environment.

Therefore, because I want to use Rmath while using a package I'm working on, I need to add Rmath as a dependency of that package, even though it itself doesn't use Rmath.
Now, building Rmath fails because it tries to run the `startup.jl` script, and building unlike testing doesn't turn on bounds checks. Meaning I now also have to add `OhMyREPL` as a dependency of the project.

I'm sure there's a much better way.

**Comment by KristofferC** [comment]
It is indeed a bug in Pkg.jl

**Comment by iht** [comment]
For the moment, I am using this workaround in `~/.julia/config/startup.jl`

```julia
try
    @eval using OhMyREPL
catch err
    @warn "Could not load OhMyREPL."
end
```

This seems to be working. I get `OhMyREPL` running in my REPL, and just the warning when I am using `Pkg`.

**Comment by long-short** [comment]
and, just commenting out "using OhMyREPL", till this gets sorted out, seems to be working too.

# using OhMyREPL

**Comment by long-short** [comment]
and, just commenting out "using OhMyREPL", till this gets sorted out, seems to be working too.

`# using` OhMyREPL

**Comment by BoundaryValueProblems** [comment]
I tried the suggestion made by @iht with Julia v1.0 on my MacBook Pro, but it still failed with the following error when I tried to build some package:
```
(v1.0) pkg> build MbedTLS
  Building MbedTLS → `~/.julia/packages/MbedTLS/McYwM/deps/build.log`
┌ Error: Error building `MbedTLS`: 
│ ┌ Warning: Could not load OhMyREPL.
│ └ @ Main ~/.julia/config/startup.jl:10
│ ERROR: LoadError: ArgumentError: Package Statistics not found in current path:
│ - Run `Pkg.add("Statistics")` to install the Statistics package.
│ 
│ Stacktrace:
│  [1] require(::Module, ::Symbol) at ./loading.jl:817
│ in expression starting at /Users/xxx/.julia/config/startup.jl:14
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068
```
This still occurs even after I install ```Statistics``` package as the error message suggested.

**Comment by BoundaryValueProblems** [comment]
I'm sorry for the last posting. The reason I got that error was that in my startup.jl, there's another line ```using Statistics```. I tried the same, i.e., suggestion B) of @iht, then it worked! However, I'm very curious, I have another line ```using LinearAlgebra```. For this package, I don't need to do the same trick B) as OhMyREPL and Statistics. Why? Just in case, that part of my current startup.jl is:
```
try
    @eval using OhMyREPL
catch err
    @warn "Could not load OhMyREPL."
end

@eval using LinearAlgebra

try
    @eval using Statistics
catch err
    @warn "Could not load Statistics."
end
```

**Comment by KristofferC** [comment]
https://kristofferc.github.io/OhMyREPL.jl/latest/installation/#Automatically-start-with-Julia.-1

now describes how to do this.

**Comment by BoundaryValueProblems** [comment]
@KristofferC ; When I added your new way to handle this in my startup.jl, I got the following error:
```
 Warning: error while importing OhMyREPL
│   e =
│    InitError: UndefRefError: access to undefined reference
│    during initialization of module OhMyREPL
└ @ Main ~/.julia/config/startup.jl:11
```
On the other hand, my previous startup.jl containing the following lines was fine:
```
try
    @eval using OhMyREPL
catch err
    @warn "Could not load OhMyREPL."
end
```
So, probably, you may want to reopen this issue.
Thanks!

**Comment by KristofferC** [comment]
No because that is fixed in the new version that I just tagged.
