### ISSUE TITLE
redirecting stderr at load time is fragile and will hide real issues

### ISSUE THREAD

**Issue by tkelman** [KristofferC/OhMyREPL.jl#70]
suppressing warnings (which are there because this package does things most code shouldn't) is going to also silently swallow any real errors or deprecations

**Comment by KristofferC** [comment]
Do what do you suggest?

**Comment by tkelman** [comment]
Don't redirect stderr. Or check that its content matches exactly what you expect it to, and only hide it if it does.

**Comment by KristofferC** [comment]
> Don't redirect stderr.

That will not happen.

I might try something like https://github.com/cstjean/ClobberingReload.jl/blob/master/src/scrub_stderr.jl.

**Comment by tkelman** [comment]
An API that allows you to do what you want to without redefining methods, sure. Redefining methods is something that should be warned about.

**Comment by KristofferC** [comment]
You realize that the whole point of this package right?

**Comment by tkelman** [comment]
re: https://github.com/KristofferC/OhMyREPL.jl/pull/97#issuecomment-320230094

I apologize for the harsh language, but I'm specifically referring only to https://github.com/KristofferC/OhMyREPL.jl/blob/v0.2.7/src/OhMyREPL.jl#L126-L130. Which you've acknowledged elsewhere is a hack that you'd rather not have to do.

It's the monkey patching that shouldn't be necessary long term. We have a ways to go still, but the fact that you have to monkey patch them means the Base API's still need work.

**Comment by KristofferC** [comment]
#99
