### ISSUE TITLE
improve experience when typing the first word in a repl session

### ISSUE THREAD

**Issue by innerlee** [KristofferC/OhMyREPL.jl#74]
OS: Ubuntu,
Julia: 0.5.2

The package is loaded from ``.juliarc.jl``. There are some laggy (1~2s) when typing the very first character in a repl session. Can this be improved?

**Comment by KristofferC** [comment]
It should be bit better if you recompile the sysimg with OhMyREPL.jl like is described in the manual.

**Comment by innerlee** [comment]
the manual says

> have to parse and compile the package when it is loaded.

Is it possible to auto trigger the parse and compile thing after julia starts (repl shows in the terminal), but before user type the first word?

**Comment by KristofferC** [comment]
Perhaps, I'll look into it.

**Comment by KristofferC** [comment]
I think this is pretty ok now
