### ISSUE TITLE
prompt pasting is not working in windows 10 (in both cmd & PS)

### ISSUE THREAD

**Issue by DrKrar** [KristofferC/OhMyREPL.jl#75]
it seems to me that prompt pasting is not working
![image](https://cloud.githubusercontent.com/assets/1588708/26360264/f641d89e-3fd7-11e7-8c42-3dcea794240c.png)

![image](https://cloud.githubusercontent.com/assets/1588708/26360413/53d530a0-3fd8-11e7-91c5-cdb97f5dab7f.png)

**Comment by KristofferC** [comment]
On windows with standard cmd, prompt pasting will not work. This is described in the warning box in the documentation: https://kristofferc.github.io/OhMyREPL.jl/latest/features/prompt_pasting.html.The reason for this is that cmd in Windows does not support bracket pasting.

**Comment by DrKrar** [comment]
I am running windows 10, it did not work for PS in admin mode.
![image](https://cloud.githubusercontent.com/assets/1588708/26366711/62c01ecc-3fec-11e7-8a7d-005da53adbea.png)

**Comment by KristofferC** [comment]
You need a terminal that supports bracket pasting (cygwin, cmder etc).

**Comment by DrKrar** [comment]
As i get it is a feature that depend on the underline shell. thanks
```
You need a terminal that supports bracket pasting (cygwin, cmder etc).
```
I think clearing the issue would be of benfite to thw Windows users who are not familiar.

**Comment by KristofferC** [comment]
Done in https://github.com/KristofferC/OhMyREPL.jl/commit/c38c63d97930d973585ca20bf8c66a894d441fe8

**Comment by DrKrar** [comment]
Thanks very much for ur effort. I would love to use the feature on my pc.
 again thanks
