### ISSUE TITLE
Highlighting of dotted calls

### ISSUE THREAD

**Issue by DNF2** [KristofferC/OhMyREPL.jl#94]
Syntax highlighting of calls is lost when using dot broadcast syntax:

<img width="168" alt="screen shot 2017-07-31 at 23 34 05" src="https://user-images.githubusercontent.com/7106412/28799505-2278c1f0-7649-11e7-97e7-5777c593c2e3.png">

**Comment by KristofferC** [comment]
Can you try: https://github.com/KristofferC/OhMyREPL.jl/issues/94

**Comment by DNF2** [comment]
Thanks for the quick response. I'm a bit of a klutz when it comes to git, though. I tried `Pkg.checkout("OhMyREPL", "dots")` and `Pkg.checkout("OhMyREPL", "kc/dots")`, but I just get
```
ERROR: GitError(Code:ERROR, Class:Merge, There is no tracking information for the current branch.)
```
`Pkg.checkout("OhMyREPL")` works fine, not sure how to proceed.

**Comment by KristofferC** [comment]
Try to navigate to `.julia/v0.6/OhMyREPL`, run `git fetch` and then `git checkout kc/dots`.

**Comment by DNF2** [comment]
That worked. And highlighting with dots is now working as expected.
